PACKAGE=w3c.www.mux

FILES = \
	MUX.java \
	MuxInputStream.java \
	MuxOutputStream.java \
	MuxReader.java \
	MuxSession.java \
	MuxStream.java \
	MuxWriter.java \
	MuxStreamHandler.java \
	MuxProtocolHandler.java \
	SampleMuxHandler.java

PACKAGES = \
	handlers \
	tests

include $(MAKEDIR)/file.make
include $(MAKEDIR)/package.make
