PACKAGE = "w3c.www.mime"

FILES = \
	MimeHeaderHolder.java \
	MimeParser.java \
	MimeParserException.java \
	MimeParserFactory.java \
	MimeType.java \
	MimeTypeFormatException.java \
	MultipartInputStream.java \
	MimeHeaders.java \
	MimeHeadersFactory.java

include $(MAKEDIR)/file.make
