PACKAGE="w3c.tools.store"

FILES = \
	Attribute.java \
	AttributeHolder.java \
	AttributeHolderAttribute.java \
	AttributeRegistry.java \
	BooleanAttribute.java \
	ClassAttribute.java \
	DateAttribute.java \
	DoubleAttribute.java \
	FileAttribute.java \
	FilenameAttribute.java \
	HolderInitException.java \
	IllegalAttributeAccess.java \
	IntegerArrayAttribute.java \
	IntegerAttribute.java \
	InvalidResourceException.java \
	LongAttribute.java \
	MimeTypeAttribute.java \
	ObjectAttribute.java \
	PropertiesAttribute.java \
	Resource.java \
	ResourceLocker.java \
	ResourceShadower.java \
	ResourceStore.java \
	ResourceStoreHolder.java \
	ResourceStoreManager.java \
	SimpleResourceStore.java \
	StringArrayAttribute.java \
	StringAttribute.java \
	jdbmResourceStore.java \
	NotAStoreException.java \
	InvalidStoreClassException.java \
	StoreClassVersionException.java \
	ResourceWalker.java \
	WalkerEngine.java \
	ContainerInterface.java \
	ResourceStoreState.java \
	SampleContainer.java \
	ResourceFrame.java \
	FrameArrayAttribute.java

include $(MAKEDIR)/file.make
