/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_biss_awt_kernel_Toolkit
#define _Included_biss_awt_kernel_Toolkit

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class biss_awt_kernel_Toolkit */

typedef struct Classbiss_awt_kernel_Toolkit {
  struct Hbiss_awt_kernel_NativeLib* Lib;
  struct Hbiss_Queue* CreateQueue;
  struct Hbiss_awt_kernel_Graphics* PaintGraphics;
  HArrayOfObject* PeerTable;
  struct Hjava_lang_String* Name;
  struct Hjava_lang_Thread* EventThread;
} Classbiss_awt_kernel_Toolkit;
HandleTo(biss_awt_kernel_Toolkit);


#ifdef __cplusplus
}
#endif

#endif
