/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_biss_awt_kernel_Graphics
#define _Included_biss_awt_kernel_Graphics

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class biss_awt_kernel_Graphics */

typedef struct Classbiss_awt_kernel_Graphics {
  struct Hbiss_awt_kernel_NativeLib* Lib;
  struct Hjava_awt_peer_ComponentPeer* Wnd;
  struct Hjava_awt_Image* Img;
  struct Hjava_awt_Rectangle* ClipRect;
  struct Hjava_awt_Color* CurrentColor;
  struct Hjava_awt_Font* CurrentFont;
  struct Hjava_awt_Color* XorColor;
  int __dummy7;
  jlong PData;
  jint XOrigin;
  jint YOrigin;
} Classbiss_awt_kernel_Graphics;
HandleTo(biss_awt_kernel_Graphics);


#ifdef __cplusplus
}
#endif

#endif
