/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_biss_awt_kernel_NativeLib
#define _Included_biss_awt_kernel_NativeLib

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class biss_awt_kernel_NativeLib */

typedef struct Classbiss_awt_kernel_NativeLib {
  jint /* bool */ SyncHint;
  jint /* bool */ HasKernelThreads;
  jint /* bool */ UseBackingStore;
  jint Width;
  jint Height;
  jint Resolution;
  struct Hjava_awt_Toolkit* Tk;
  jint VisualClass;
  jint EventsAvailable;
  struct Hjava_awt_Event* NextEvent;
  struct Hjava_lang_Object* RecycledPeer;
  HArrayOfObject* PeerTable;
  struct Hjava_lang_String* Name;
  jint /* bool */ AttentionHint;
  jint /* bool */ PopDownHint;
  int __dummy15;
  jlong PData;
  jint /* bool */ ShrinkFrame;
} Classbiss_awt_kernel_NativeLib;
HandleTo(biss_awt_kernel_NativeLib);

extern void biss_awt_kernel_NativeLib_clearRect(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_clipGraphics(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*);
extern void biss_awt_kernel_NativeLib_copyArea(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_createWindow(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*);
extern void biss_awt_kernel_NativeLib_destroyWindow(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*);
extern void biss_awt_kernel_NativeLib_draw3DRect(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint, jint /* bool */, jint, struct Hjava_awt_Color*, struct Hjava_awt_Color*);
extern void biss_awt_kernel_NativeLib_drawArc(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_drawChars(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, HArrayOfChar*, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_drawImage(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, struct Hjava_awt_Image*, jint, jint, jint, jint, struct Hjava_awt_Color*);
extern void biss_awt_kernel_NativeLib_drawLine(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_drawOval(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_drawPolygon(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, HArrayOfInt*, HArrayOfInt*, jint);
extern void biss_awt_kernel_NativeLib_drawRect(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_drawRoundRect(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_drawString(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, struct Hjava_lang_String*, jint, jint);
extern void biss_awt_kernel_NativeLib_fillArc(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_fillOval(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_fillPolygon(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, HArrayOfInt*, HArrayOfInt*, jint);
extern void biss_awt_kernel_NativeLib_fillRect(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_fillRoundRect(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, jint, jint, jint, jint, jint, jint);
extern jint biss_awt_kernel_NativeLib_getNextEvent(struct Hbiss_awt_kernel_NativeLib*);
extern struct Hjava_awt_Color* biss_awt_kernel_NativeLib_getTargetBackground(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Component*);
extern struct Hjava_awt_Font* biss_awt_kernel_NativeLib_getTargetFont(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Component*);
extern struct Hjava_awt_Color* biss_awt_kernel_NativeLib_getTargetForeground(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Component*);
extern void biss_awt_kernel_NativeLib_hideWindow(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*);
extern void biss_awt_kernel_NativeLib_initBlankImage(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Image*, jint, jint);
extern void biss_awt_kernel_NativeLib_initFontMetrics(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_FontMetrics*);
extern void biss_awt_kernel_NativeLib_initGraphics(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*);
extern void biss_awt_kernel_NativeLib_initPaintGraphics(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*);
extern void biss_awt_kernel_NativeLib_initStdColor(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Color*);
extern void biss_awt_kernel_NativeLib_initialize(struct Hbiss_awt_kernel_NativeLib*);
extern void biss_awt_kernel_NativeLib_lowerWindow(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*);
extern void biss_awt_kernel_NativeLib_raiseWindow(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*);
extern void biss_awt_kernel_NativeLib_releaseFontMetrics(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_FontMetrics*);
extern void biss_awt_kernel_NativeLib_releaseGraphics(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*);
extern void biss_awt_kernel_NativeLib_releaseImage(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Image*);
extern void biss_awt_kernel_NativeLib_releasePaintGraphics(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*);
extern void biss_awt_kernel_NativeLib_repaintWindow(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*, jlong, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_reshapeWindow(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*, jint, jint, jint, jint);
extern void biss_awt_kernel_NativeLib_setColor(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, struct Hjava_awt_Color*);
extern void biss_awt_kernel_NativeLib_setDebugLevel(struct Hbiss_awt_kernel_NativeLib*, jint);
extern void biss_awt_kernel_NativeLib_setFocusWindow(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*);
extern void biss_awt_kernel_NativeLib_setFont(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*, struct Hjava_awt_Font*);
extern void biss_awt_kernel_NativeLib_setPaintMode(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*);
extern void biss_awt_kernel_NativeLib_setStdFontSpec(struct Hbiss_awt_kernel_NativeLib*, jint, struct Hjava_lang_String*);
extern void biss_awt_kernel_NativeLib_setWindowBackground(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*, struct Hjava_awt_Color*);
extern void biss_awt_kernel_NativeLib_setWindowCursor(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*, jint);
extern void biss_awt_kernel_NativeLib_setWindowTitle(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*, struct Hjava_lang_String*);
extern void biss_awt_kernel_NativeLib_setXORMode(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_Graphics*);
extern void biss_awt_kernel_NativeLib_showWindow(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_peer_ComponentPeer*);
extern jint biss_awt_kernel_NativeLib_stringWidth(struct Hbiss_awt_kernel_NativeLib*, struct Hjava_awt_FontMetrics*, struct Hjava_lang_String*);
extern void biss_awt_kernel_NativeLib_sync(struct Hbiss_awt_kernel_NativeLib*);

#ifdef __cplusplus
}
#endif

#endif
