/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_biss_awt_MutableIndexClrModel
#define _Included_biss_awt_MutableIndexClrModel

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class biss_awt_MutableIndexClrModel */

typedef struct Classbiss_awt_MutableIndexClrModel {
  jint pData;
  jint pixel_bits;
  HArrayOfInt* Rgb;
  jint Transparent;
} Classbiss_awt_MutableIndexClrModel;
HandleTo(biss_awt_MutableIndexClrModel);


#ifdef __cplusplus
}
#endif

#endif
