/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_biss_awt_kernel_FontMetrics
#define _Included_biss_awt_kernel_FontMetrics

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class biss_awt_kernel_FontMetrics */

typedef struct Classbiss_awt_kernel_FontMetrics {
  struct Hjava_awt_Font* font;
  struct Hbiss_awt_kernel_NativeLib* Lib;
  jint /* bool */ IsFixed;
  HArrayOfInt* Widths;
  jint Width;
  jint Height;
  jint Descent;
  jint Ascent;
  jint Leading;
  jint MaxAdvance;
  jint MaxDescent;
  jint MaxAscent;
  jint /* bool */ IsWideFont;
  int __dummy13;
  jlong PData;
} Classbiss_awt_kernel_FontMetrics;
HandleTo(biss_awt_kernel_FontMetrics);


#ifdef __cplusplus
}
#endif

#endif
