/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_Graphics
#define _Included_java_awt_Graphics

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_Graphics */

typedef struct Classjava_awt_Graphics {
	int __DUMMY__;
} Classjava_awt_Graphics;
HandleTo(java_awt_Graphics);


#ifdef __cplusplus
}
#endif

#endif
