/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_Toolkit
#define _Included_java_awt_Toolkit

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_Toolkit */

typedef struct Classjava_awt_Toolkit {
	int __DUMMY__;
} Classjava_awt_Toolkit;
HandleTo(java_awt_Toolkit);


#ifdef __cplusplus
}
#endif

#endif
