/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_Component
#define _Included_java_awt_Component

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_Component */

typedef struct Classjava_awt_Component {
  struct Hjava_awt_peer_ComponentPeer* peer;
  struct Hjava_awt_Container* parent;
  jint x;
  jint y;
  jint width;
  jint height;
  struct Hjava_awt_Color* foreground;
  struct Hjava_awt_Color* background;
  struct Hjava_awt_Font* font;
  jint /* bool */ visible;
  jint /* bool */ enabled;
  jint /* bool */ valid;
} Classjava_awt_Component;
HandleTo(java_awt_Component);


#ifdef __cplusplus
}
#endif

#endif
