/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_image_ImageObserver
#define _Included_java_awt_image_ImageObserver

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_image_ImageObserver */

typedef struct Classjava_awt_image_ImageObserver {
#define java_awt_image_ImageObserver_WIDTH 1
#define java_awt_image_ImageObserver_HEIGHT 2
#define java_awt_image_ImageObserver_PROPERTIES 4
#define java_awt_image_ImageObserver_SOMEBITS 8
#define java_awt_image_ImageObserver_FRAMEBITS 16
#define java_awt_image_ImageObserver_ALLBITS 32
#define java_awt_image_ImageObserver_ERROR 64
#define java_awt_image_ImageObserver_ABORT 128
	int __DUMMY__;
} Classjava_awt_image_ImageObserver;
HandleTo(java_awt_image_ImageObserver);


#ifdef __cplusplus
}
#endif

#endif
