/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_Frame
#define _Included_java_awt_Frame

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_Frame */

typedef struct Classjava_awt_Frame {
  struct Hjava_awt_peer_ComponentPeer* peer;
  struct Hjava_awt_Container* parent;
  jint x;
  jint y;
  jint width;
  jint height;
  struct Hjava_awt_Color* foreground;
  struct Hjava_awt_Color* background;
  struct Hjava_awt_Font* font;
  jint /* bool */ visible;
  jint /* bool */ enabled;
  jint /* bool */ valid;
  jint ncomponents;
  HArrayOfObject* component;
  struct Hjava_awt_LayoutManager* layoutMgr;
  struct Hjava_lang_String* warningString;
  struct Hjava_awt_FocusManager* focusMgr;
#define java_awt_Frame_DEFAULT_CURSOR 0
#define java_awt_Frame_CROSSHAIR_CURSOR 1
#define java_awt_Frame_TEXT_CURSOR 2
#define java_awt_Frame_WAIT_CURSOR 3
#define java_awt_Frame_SW_RESIZE_CURSOR 4
#define java_awt_Frame_SE_RESIZE_CURSOR 5
#define java_awt_Frame_NW_RESIZE_CURSOR 6
#define java_awt_Frame_NE_RESIZE_CURSOR 7
#define java_awt_Frame_N_RESIZE_CURSOR 8
#define java_awt_Frame_S_RESIZE_CURSOR 9
#define java_awt_Frame_W_RESIZE_CURSOR 10
#define java_awt_Frame_E_RESIZE_CURSOR 11
#define java_awt_Frame_HAND_CURSOR 12
#define java_awt_Frame_MOVE_CURSOR 13
  struct Hjava_lang_String* title;
  struct Hjava_awt_Image* icon;
  struct Hjava_awt_MenuBar* menuBar;
  jint /* bool */ resizable;
  struct Hjava_awt_Image* cursorImage;
  jint cursorType;
  struct Hjava_awt_Color* cursorFg;
  struct Hjava_awt_Color* cursorBg;
} Classjava_awt_Frame;
HandleTo(java_awt_Frame);


#ifdef __cplusplus
}
#endif

#endif
