/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_image_IndexColorModel
#define _Included_java_awt_image_IndexColorModel

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_image_IndexColorModel */

typedef struct Classjava_awt_image_IndexColorModel {
  jint pData;
  jint pixel_bits;
  HArrayOfInt* rgb;
  jint map_size;
  jint /* bool */ opaque;
  jint transparent_index;
} Classjava_awt_image_IndexColorModel;
HandleTo(java_awt_image_IndexColorModel);


#ifdef __cplusplus
}
#endif

#endif
