/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_Event
#define _Included_java_awt_Event

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_Event */

typedef struct Classjava_awt_Event {
  jint data;
#define java_awt_Event_SHIFT_MASK 1
#define java_awt_Event_CTRL_MASK 2
#define java_awt_Event_META_MASK 4
#define java_awt_Event_ALT_MASK 8
#define java_awt_Event_HOME 1000
#define java_awt_Event_END 1001
#define java_awt_Event_PGUP 1002
#define java_awt_Event_PGDN 1003
#define java_awt_Event_UP 1004
#define java_awt_Event_DOWN 1005
#define java_awt_Event_LEFT 1006
#define java_awt_Event_RIGHT 1007
#define java_awt_Event_F1 1008
#define java_awt_Event_F2 1009
#define java_awt_Event_F3 1010
#define java_awt_Event_F4 1011
#define java_awt_Event_F5 1012
#define java_awt_Event_F6 1013
#define java_awt_Event_F7 1014
#define java_awt_Event_F8 1015
#define java_awt_Event_F9 1016
#define java_awt_Event_F10 1017
#define java_awt_Event_F11 1018
#define java_awt_Event_F12 1019
#define java_awt_Event_WINDOW_DESTROY 201
#define java_awt_Event_WINDOW_EXPOSE 202
#define java_awt_Event_WINDOW_ICONIFY 203
#define java_awt_Event_WINDOW_DEICONIFY 204
#define java_awt_Event_WINDOW_MOVED 205
#define java_awt_Event_KEY_PRESS 401
#define java_awt_Event_KEY_RELEASE 402
#define java_awt_Event_KEY_ACTION 403
#define java_awt_Event_KEY_ACTION_RELEASE 404
#define java_awt_Event_MOUSE_DOWN 501
#define java_awt_Event_MOUSE_UP 502
#define java_awt_Event_MOUSE_MOVE 503
#define java_awt_Event_MOUSE_ENTER 504
#define java_awt_Event_MOUSE_EXIT 505
#define java_awt_Event_MOUSE_DRAG 506
#define java_awt_Event_SCROLL_LINE_UP 601
#define java_awt_Event_SCROLL_LINE_DOWN 602
#define java_awt_Event_SCROLL_PAGE_UP 603
#define java_awt_Event_SCROLL_PAGE_DOWN 604
#define java_awt_Event_SCROLL_ABSOLUTE 605
#define java_awt_Event_LIST_SELECT 701
#define java_awt_Event_LIST_DESELECT 702
#define java_awt_Event_ACTION_EVENT 1001
#define java_awt_Event_LOAD_FILE 1002
#define java_awt_Event_SAVE_FILE 1003
#define java_awt_Event_GOT_FOCUS 1004
#define java_awt_Event_LOST_FOCUS 1005
  struct Hjava_lang_Object* target;
  jlong when;
  jint id;
  jint x;
  jint y;
  jint key;
  jint modifiers;
  jint clickCount;
  struct Hjava_lang_Object* arg;
  struct Hjava_awt_Event* evt;
} Classjava_awt_Event;
HandleTo(java_awt_Event);


#ifdef __cplusplus
}
#endif

#endif
