PACKAGE = "w3c.www.http"

FILES = \
	HTTP.java \
	BasicValue.java \
	HeaderDescription.java \
	HeaderValue.java \
	HttpAccessException.java \
	HttpBuffer.java \
	HttpCacheControl.java \
	HttpDate.java \
	HttpEntityMessage.java \
	HttpEntityTag.java \
	HttpEntityTagList.java \
	HttpInteger.java \
	HttpMessage.java \
	HttpMimeType.java \
	HttpParser.java \
	HttpParserException.java \
	HttpContentRange.java \
	HttpReplyMessage.java \
	HttpRequestMessage.java \
	HttpString.java \
	HttpTokenList.java \
	HttpCaseTokenList.java \
	HttpUpperTokenList.java \
	MimeParserMessageFactory.java \
	MimeParserReplyFactory.java \
	MimeParserRequestFactory.java \
	ContentLengthInputStream.java \
	ChunkedInputStream.java \
	HttpWarning.java \
	HttpWarningList.java \
	HttpStreamObserver.java \
	HttpAccept.java \
	HttpAcceptList.java \
	HttpAcceptLanguage.java \
	HttpAcceptLanguageList.java \
	HttpAcceptCharset.java \
	HttpAcceptCharsetList.java \
	HttpRange.java \
	HttpRangeList.java \
	HttpCredential.java \
	HttpChallenge.java \
	HttpBag.java \
	ParseState.java \
	HttpSetCookieList.java \
	HttpCookieList.java \
	HttpCookie.java \
	HttpSetCookie.java \
	headerEnumerator.java \
	HttpFactory.java \
	HttpInvalidValueException.java \
	ChunkedOutputStream.java \
	ByteRangeOutputStream.java


include $(MAKEDIR)/file.make

