/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_util_Date
#define _Included_java_util_Date

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_util_Date */

typedef struct Classjava_util_Date {
  jlong value;
  jint /* bool */ valueValid;
  jint /* bool */ expanded;
  jint /* short */ tm_millis;
  jint /* byte */ tm_sec;
  jint /* byte */ tm_min;
  jint /* byte */ tm_hour;
  jint /* byte */ tm_mday;
  jint /* byte */ tm_mon;
  jint /* byte */ tm_wday;
  jint /* short */ tm_yday;
  jint tm_year;
  jint tm_isdst;
} Classjava_util_Date;
HandleTo(java_util_Date);

extern struct Hjava_lang_String* java_util_Date_toString(struct Hjava_util_Date*);
extern struct Hjava_lang_String* java_util_Date_toLocaleString(struct Hjava_util_Date*);
extern struct Hjava_lang_String* java_util_Date_toGMTString(struct Hjava_util_Date*);
extern void java_util_Date_expand(struct Hjava_util_Date*);
extern void java_util_Date_computeValue(struct Hjava_util_Date*);

#ifdef __cplusplus
}
#endif

#endif
