/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_util_Date */

/* SYMBOL: java_util_Date_toString()Ljava/lang/String; */
void
Kaffe_java_util_Date_toString_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_util_Date_toString(void*);
	struct Hjava_lang_String* ret = java_util_Date_toString(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_util_Date_toLocaleString()Ljava/lang/String; */
void
Kaffe_java_util_Date_toLocaleString_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_util_Date_toLocaleString(void*);
	struct Hjava_lang_String* ret = java_util_Date_toLocaleString(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_util_Date_toGMTString()Ljava/lang/String; */
void
Kaffe_java_util_Date_toGMTString_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_util_Date_toGMTString(void*);
	struct Hjava_lang_String* ret = java_util_Date_toGMTString(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_util_Date_expand()V */
void
Kaffe_java_util_Date_expand_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_util_Date_expand(void*);
	java_util_Date_expand(_P_[0].p);
}

/* SYMBOL: java_util_Date_computeValue()V */
void
Kaffe_java_util_Date_computeValue_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_util_Date_computeValue(void*);
	java_util_Date_computeValue(_P_[0].p);
}
