/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Class */

/* SYMBOL: java_lang_Class_forName(Ljava/lang/String;)Ljava/lang/Class; */
void
Kaffe_java_lang_Class_forName_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Class* java_lang_Class_forName(void*, void*);
	struct Hjava_lang_Class* ret = java_lang_Class_forName(0, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_newInstance()Ljava/lang/Object; */
void
Kaffe_java_lang_Class_newInstance_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* java_lang_Class_newInstance(void*);
	struct Hjava_lang_Object* ret = java_lang_Class_newInstance(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getName()Ljava/lang/String; */
void
Kaffe_java_lang_Class_getName_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_lang_Class_getName(void*);
	struct Hjava_lang_String* ret = java_lang_Class_getName(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getSuperclass()Ljava/lang/Class; */
void
Kaffe_java_lang_Class_getSuperclass_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Class* java_lang_Class_getSuperclass(void*);
	struct Hjava_lang_Class* ret = java_lang_Class_getSuperclass(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getInterfaces()[Ljava/lang/Class; */
void
Kaffe_java_lang_Class_getInterfaces_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* java_lang_Class_getInterfaces(void*);
	HArrayOfObject* ret = java_lang_Class_getInterfaces(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getClassLoader()Ljava/lang/ClassLoader; */
void
Kaffe_java_lang_Class_getClassLoader_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_ClassLoader* java_lang_Class_getClassLoader(void*);
	struct Hjava_lang_ClassLoader* ret = java_lang_Class_getClassLoader(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_isInterface()Z */
void
Kaffe_java_lang_Class_isInterface_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint /* bool */ java_lang_Class_isInterface(void*);
	jint /* bool */ ret = java_lang_Class_isInterface(_P_[0].p);
	return_int(ret);
}
