/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Double */

/* SYMBOL: java_lang_Double_toString(D)Ljava/lang/String; */
void
Kaffe_java_lang_Double_toString_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_lang_Double_toString(void*, jdouble);
	struct Hjava_lang_String* ret = java_lang_Double_toString(0, _P_[0].d);
	return_ref(ret);
}

/* SYMBOL: java_lang_Double_valueOf(Ljava/lang/String;)Ljava/lang/Double; */
void
Kaffe_java_lang_Double_valueOf_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Double* java_lang_Double_valueOf(void*, void*);
	struct Hjava_lang_Double* ret = java_lang_Double_valueOf(0, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Double_doubleToLongBits(D)J */
void
Kaffe_java_lang_Double_doubleToLongBits_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_lang_Double_doubleToLongBits(void*, jdouble);
	jlong ret = java_lang_Double_doubleToLongBits(0, _P_[0].d);
	return_long(ret);
}

/* SYMBOL: java_lang_Double_longBitsToDouble(J)D */
void
Kaffe_java_lang_Double_longBitsToDouble_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Double_longBitsToDouble(void*, jlong);
	jdouble ret = java_lang_Double_longBitsToDouble(0, _P_[0].l);
	return_double(ret);
}
