/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Math */

/* SYMBOL: java_lang_Math_sin(D)D */
void
Kaffe_java_lang_Math_sin_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_sin(void*, jdouble);
	jdouble ret = java_lang_Math_sin(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_cos(D)D */
void
Kaffe_java_lang_Math_cos_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_cos(void*, jdouble);
	jdouble ret = java_lang_Math_cos(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_tan(D)D */
void
Kaffe_java_lang_Math_tan_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_tan(void*, jdouble);
	jdouble ret = java_lang_Math_tan(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_asin(D)D */
void
Kaffe_java_lang_Math_asin_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_asin(void*, jdouble);
	jdouble ret = java_lang_Math_asin(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_acos(D)D */
void
Kaffe_java_lang_Math_acos_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_acos(void*, jdouble);
	jdouble ret = java_lang_Math_acos(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_atan(D)D */
void
Kaffe_java_lang_Math_atan_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_atan(void*, jdouble);
	jdouble ret = java_lang_Math_atan(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_exp(D)D */
void
Kaffe_java_lang_Math_exp_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_exp(void*, jdouble);
	jdouble ret = java_lang_Math_exp(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_log(D)D */
void
Kaffe_java_lang_Math_log_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_log(void*, jdouble);
	jdouble ret = java_lang_Math_log(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_sqrt(D)D */
void
Kaffe_java_lang_Math_sqrt_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_sqrt(void*, jdouble);
	jdouble ret = java_lang_Math_sqrt(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_IEEEremainder(DD)D */
void
Kaffe_java_lang_Math_IEEEremainder_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_IEEEremainder(void*, jdouble, jdouble);
	jdouble ret = java_lang_Math_IEEEremainder(0, _P_[2].d, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_ceil(D)D */
void
Kaffe_java_lang_Math_ceil_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_ceil(void*, jdouble);
	jdouble ret = java_lang_Math_ceil(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_floor(D)D */
void
Kaffe_java_lang_Math_floor_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_floor(void*, jdouble);
	jdouble ret = java_lang_Math_floor(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_rint(D)D */
void
Kaffe_java_lang_Math_rint_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_rint(void*, jdouble);
	jdouble ret = java_lang_Math_rint(0, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_atan2(DD)D */
void
Kaffe_java_lang_Math_atan2_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_atan2(void*, jdouble, jdouble);
	jdouble ret = java_lang_Math_atan2(0, _P_[2].d, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_pow(DD)D */
void
Kaffe_java_lang_Math_pow_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_pow(void*, jdouble, jdouble);
	jdouble ret = java_lang_Math_pow(0, _P_[2].d, _P_[0].d);
	return_double(ret);
}
