/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_System */

/* SYMBOL: java_lang_System_currentTimeMillis()J */
void
Kaffe_java_lang_System_currentTimeMillis_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_lang_System_currentTimeMillis(void*);
	jlong ret = java_lang_System_currentTimeMillis(0);
	return_long(ret);
}

/* SYMBOL: java_lang_System_arraycopy(Ljava/lang/Object;ILjava/lang/Object;II)V */
void
Kaffe_java_lang_System_arraycopy_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_System_arraycopy(void*, void*, jint, void*, jint, jint);
	java_lang_System_arraycopy(0, _P_[4].p, _P_[3].i, _P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_lang_System_initProperties(Ljava/util/Properties;)Ljava/util/Properties; */
void
Kaffe_java_lang_System_initProperties_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_util_Properties* java_lang_System_initProperties(void*, void*);
	struct Hjava_util_Properties* ret = java_lang_System_initProperties(0, _P_[0].p);
	return_ref(ret);
}
