PACKAGE=w3c.util

FILES = \
	ArrayDictionary.java \
	ArrayEnumeration.java \
	AsyncLRUList.java \
	LRUAble.java \
	LRUList.java \
	LRUNode.java \
	SyncLRUList.java \
	TimeFormatter.java \
	ObservableProperties.java \
	PropertyMonitoring.java \
	Unix.java \
	UnixException.java \
	ThreadCache.java \
	CountOutputStream.java \
	FastByteBuffer.java \
	ByteBufferHandler.java


include $(MAKEDIR)/file.make
