/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_net_DatagramSocket
#define _Included_java_net_DatagramSocket

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_net_DatagramSocket */

typedef struct Classjava_net_DatagramSocket {
  jint localPort;
  struct Hjava_io_FileDescriptor* fd;
} Classjava_net_DatagramSocket;
HandleTo(java_net_DatagramSocket);

extern void java_net_DatagramSocket_datagramSocketCreate(struct Hjava_net_DatagramSocket*);
extern jint java_net_DatagramSocket_datagramSocketBind(struct Hjava_net_DatagramSocket*, jint);
extern void java_net_DatagramSocket_datagramSocketSend(struct Hjava_net_DatagramSocket*, struct Hjava_net_DatagramPacket*);
extern jint java_net_DatagramSocket_datagramSocketPeek(struct Hjava_net_DatagramSocket*, struct Hjava_net_InetAddress*);
extern void java_net_DatagramSocket_datagramSocketReceive(struct Hjava_net_DatagramSocket*, struct Hjava_net_DatagramPacket*);
extern void java_net_DatagramSocket_datagramSocketClose(struct Hjava_net_DatagramSocket*);

#ifdef __cplusplus
}
#endif

#endif
