PACKAGE  = "w3c.www.protocol.http"

PACKAGES = \
	cache \
	auth \
	proxy \
	icp 

FILES = \
	HttpManager.java \
	RequestFilter.java \
	RequestObserver.java \
	RequestProcessor.java \
	Reply.java \
	Request.java \
	HttpServer.java \
	HttpBasicServer.java \
	HttpURLConnection.java \
	HttpConnection.java \
	Handler.java \
	FilterEngine.java \
	DebugFilter.java \
	PropRequestFilter.java \
	RequestEvent.java \
	ContinueEvent.java \
	ConnectedEvent.java \
	HttpBasicConnection.java \
	HttpException.java \
	PropRequestFilterException.java \
	HttpServerState.java

include $(MAKEDIR)/file.make
include $(MAKEDIR)/package.make
