/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_io_FileDescriptor */

/* SYMBOL: java_io_FileDescriptor_valid()Z */
void
Kaffe_java_io_FileDescriptor_valid_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint /* bool */ java_io_FileDescriptor_valid(void*);
	jint /* bool */ ret = java_io_FileDescriptor_valid(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_io_FileDescriptor_initSystemFD(Ljava/io/FileDescriptor;I)Ljava/io/FileDescriptor; */
void
Kaffe_java_io_FileDescriptor_initSystemFD_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_io_FileDescriptor* java_io_FileDescriptor_initSystemFD(void*, void*, jint);
	struct Hjava_io_FileDescriptor* ret = java_io_FileDescriptor_initSystemFD(0, _P_[1].p, _P_[0].i);
	return_ref(ret);
}
