/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_net_InetAddress
#define _Included_java_net_InetAddress

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_net_InetAddress */

typedef struct Classjava_net_InetAddress {
  struct Hjava_lang_String* hostName;
  jint address;
  jint family;
} Classjava_net_InetAddress;
HandleTo(java_net_InetAddress);

extern struct Hjava_lang_String* java_net_InetAddress_getLocalHostName(struct Hjava_net_InetAddress*);
extern void java_net_InetAddress_makeAnyLocalAddress(struct Hjava_net_InetAddress*, struct Hjava_net_InetAddress*);
extern HArrayOfByte* java_net_InetAddress_lookupHostAddr(struct Hjava_net_InetAddress*, struct Hjava_lang_String*);
extern HArrayOfArray* java_net_InetAddress_lookupAllHostAddr(struct Hjava_net_InetAddress*, struct Hjava_lang_String*);
extern struct Hjava_lang_String* java_net_InetAddress_getHostByAddr(struct Hjava_net_InetAddress*, jint);
extern jint java_net_InetAddress_getInetFamily(struct Hjava_net_InetAddress*);

#ifdef __cplusplus
}
#endif

#endif
