/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_biss_awt_kernel_Image
#define _Included_biss_awt_kernel_Image

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class biss_awt_kernel_Image */

typedef struct Classbiss_awt_kernel_Image {
  struct Hbiss_awt_kernel_NativeLib* Lib;
  jint Width;
  jint Height;
  struct Hjava_awt_image_ImageProducer* Source;
  jint Background;
  struct Hjava_awt_image_ColorModel* Model;
  struct Hjava_lang_Object* Pixels;
  struct Hjava_util_Hashtable* Props;
  struct Hjava_awt_image_ImageConsumer* Consumer;
  jint State;
  struct Hjava_awt_image_ImageObserver* Obs;
  int __dummy11;
  jlong PDataPix;
  jlong PDataImg;
  jint ModelType;
} Classbiss_awt_kernel_Image;
HandleTo(biss_awt_kernel_Image);


#ifdef __cplusplus
}
#endif

#endif
