/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_biss_awt_kernel_Peer
#define _Included_biss_awt_kernel_Peer

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class biss_awt_kernel_Peer */

typedef struct Classbiss_awt_kernel_Peer {
  struct Hbiss_awt_kernel_NativeLib* Lib;
  struct Hbiss_awt_kernel_Peer* Parent;
  struct Hjava_awt_Insets* Inset;
  jint Type;
  struct Hjava_awt_Component* Target;
  jint /* bool */ IsExposed;
  jint /* bool */ IsDisabled;
  struct Hbiss_awt_BarMenu* BM;
  jlong PData;
  struct Hjava_awt_Color* Background;
} Classbiss_awt_kernel_Peer;
HandleTo(biss_awt_kernel_Peer);


#ifdef __cplusplus
}
#endif

#endif
