/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class biss_awt_kernel_NativeLib */

/* SYMBOL: biss_awt_kernel_NativeLib_clearRect(Ljava/awt/Graphics;IIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_clearRect_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_clearRect(void*, void*, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_clearRect(_P_[5].p, _P_[4].p, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_clipGraphics(Ljava/awt/Graphics;)V */
void
Kaffe_biss_awt_kernel_NativeLib_clipGraphics_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_clipGraphics(void*, void*);
	biss_awt_kernel_NativeLib_clipGraphics(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_copyArea(Ljava/awt/Graphics;IIIIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_copyArea_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_copyArea(void*, void*, jint, jint, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_copyArea(_P_[7].p, _P_[6].p, _P_[5].i, _P_[4].i, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_createWindow(Ljava/awt/peer/ComponentPeer;)V */
void
Kaffe_biss_awt_kernel_NativeLib_createWindow_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_createWindow(void*, void*);
	biss_awt_kernel_NativeLib_createWindow(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_destroyWindow(Ljava/awt/peer/ComponentPeer;)V */
void
Kaffe_biss_awt_kernel_NativeLib_destroyWindow_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_destroyWindow(void*, void*);
	biss_awt_kernel_NativeLib_destroyWindow(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_draw3DRect(Ljava/awt/Graphics;IIIIZILjava/awt/Color;Ljava/awt/Color;)V */
void
Kaffe_biss_awt_kernel_NativeLib_draw3DRect_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_draw3DRect(void*, void*, jint, jint, jint, jint, jint /* bool */, jint, void*, void*);
	biss_awt_kernel_NativeLib_draw3DRect(_P_[9].p, _P_[8].p, _P_[7].i, _P_[6].i, _P_[5].i, _P_[4].i, _P_[3].i, _P_[2].i, _P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_drawArc(Ljava/awt/Graphics;IIIIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_drawArc_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_drawArc(void*, void*, jint, jint, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_drawArc(_P_[7].p, _P_[6].p, _P_[5].i, _P_[4].i, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_drawChars(Ljava/awt/Graphics;[CIIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_drawChars_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_drawChars(void*, void*, HArrayOfChar*, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_drawChars(_P_[6].p, _P_[5].p, _P_[4].p, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_drawImage(Ljava/awt/Graphics;Ljava/awt/Image;IIIILjava/awt/Color;)V */
void
Kaffe_biss_awt_kernel_NativeLib_drawImage_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_drawImage(void*, void*, void*, jint, jint, jint, jint, void*);
	biss_awt_kernel_NativeLib_drawImage(_P_[7].p, _P_[6].p, _P_[5].p, _P_[4].i, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_drawLine(Ljava/awt/Graphics;IIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_drawLine_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_drawLine(void*, void*, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_drawLine(_P_[5].p, _P_[4].p, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_drawOval(Ljava/awt/Graphics;IIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_drawOval_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_drawOval(void*, void*, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_drawOval(_P_[5].p, _P_[4].p, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_drawPolygon(Ljava/awt/Graphics;[I[II)V */
void
Kaffe_biss_awt_kernel_NativeLib_drawPolygon_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_drawPolygon(void*, void*, HArrayOfInt*, HArrayOfInt*, jint);
	biss_awt_kernel_NativeLib_drawPolygon(_P_[4].p, _P_[3].p, _P_[2].p, _P_[1].p, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_drawRect(Ljava/awt/Graphics;IIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_drawRect_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_drawRect(void*, void*, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_drawRect(_P_[5].p, _P_[4].p, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_drawRoundRect(Ljava/awt/Graphics;IIIIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_drawRoundRect_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_drawRoundRect(void*, void*, jint, jint, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_drawRoundRect(_P_[7].p, _P_[6].p, _P_[5].i, _P_[4].i, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_drawString(Ljava/awt/Graphics;Ljava/lang/String;II)V */
void
Kaffe_biss_awt_kernel_NativeLib_drawString_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_drawString(void*, void*, void*, jint, jint);
	biss_awt_kernel_NativeLib_drawString(_P_[4].p, _P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_fillArc(Ljava/awt/Graphics;IIIIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_fillArc_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_fillArc(void*, void*, jint, jint, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_fillArc(_P_[7].p, _P_[6].p, _P_[5].i, _P_[4].i, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_fillOval(Ljava/awt/Graphics;IIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_fillOval_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_fillOval(void*, void*, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_fillOval(_P_[5].p, _P_[4].p, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_fillPolygon(Ljava/awt/Graphics;[I[II)V */
void
Kaffe_biss_awt_kernel_NativeLib_fillPolygon_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_fillPolygon(void*, void*, HArrayOfInt*, HArrayOfInt*, jint);
	biss_awt_kernel_NativeLib_fillPolygon(_P_[4].p, _P_[3].p, _P_[2].p, _P_[1].p, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_fillRect(Ljava/awt/Graphics;IIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_fillRect_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_fillRect(void*, void*, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_fillRect(_P_[5].p, _P_[4].p, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_fillRoundRect(Ljava/awt/Graphics;IIIIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_fillRoundRect_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_fillRoundRect(void*, void*, jint, jint, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_fillRoundRect(_P_[7].p, _P_[6].p, _P_[5].i, _P_[4].i, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_getNextEvent()I */
void
Kaffe_biss_awt_kernel_NativeLib_getNextEvent_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint biss_awt_kernel_NativeLib_getNextEvent(void*);
	jint ret = biss_awt_kernel_NativeLib_getNextEvent(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: biss_awt_kernel_NativeLib_getTargetBackground(Ljava/awt/Component;)Ljava/awt/Color; */
void
Kaffe_biss_awt_kernel_NativeLib_getTargetBackground_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_awt_Color* biss_awt_kernel_NativeLib_getTargetBackground(void*, void*);
	struct Hjava_awt_Color* ret = biss_awt_kernel_NativeLib_getTargetBackground(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: biss_awt_kernel_NativeLib_getTargetFont(Ljava/awt/Component;)Ljava/awt/Font; */
void
Kaffe_biss_awt_kernel_NativeLib_getTargetFont_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_awt_Font* biss_awt_kernel_NativeLib_getTargetFont(void*, void*);
	struct Hjava_awt_Font* ret = biss_awt_kernel_NativeLib_getTargetFont(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: biss_awt_kernel_NativeLib_getTargetForeground(Ljava/awt/Component;)Ljava/awt/Color; */
void
Kaffe_biss_awt_kernel_NativeLib_getTargetForeground_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_awt_Color* biss_awt_kernel_NativeLib_getTargetForeground(void*, void*);
	struct Hjava_awt_Color* ret = biss_awt_kernel_NativeLib_getTargetForeground(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: biss_awt_kernel_NativeLib_hideWindow(Ljava/awt/peer/ComponentPeer;)V */
void
Kaffe_biss_awt_kernel_NativeLib_hideWindow_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_hideWindow(void*, void*);
	biss_awt_kernel_NativeLib_hideWindow(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_initBlankImage(Ljava/awt/Image;II)V */
void
Kaffe_biss_awt_kernel_NativeLib_initBlankImage_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_initBlankImage(void*, void*, jint, jint);
	biss_awt_kernel_NativeLib_initBlankImage(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_initFontMetrics(Ljava/awt/FontMetrics;)V */
void
Kaffe_biss_awt_kernel_NativeLib_initFontMetrics_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_initFontMetrics(void*, void*);
	biss_awt_kernel_NativeLib_initFontMetrics(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_initGraphics(Ljava/awt/Graphics;)V */
void
Kaffe_biss_awt_kernel_NativeLib_initGraphics_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_initGraphics(void*, void*);
	biss_awt_kernel_NativeLib_initGraphics(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_initPaintGraphics(Ljava/awt/Graphics;)V */
void
Kaffe_biss_awt_kernel_NativeLib_initPaintGraphics_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_initPaintGraphics(void*, void*);
	biss_awt_kernel_NativeLib_initPaintGraphics(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_initStdColor(Ljava/awt/Color;)V */
void
Kaffe_biss_awt_kernel_NativeLib_initStdColor_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_initStdColor(void*, void*);
	biss_awt_kernel_NativeLib_initStdColor(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_initialize()V */
void
Kaffe_biss_awt_kernel_NativeLib_initialize_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_initialize(void*);
	biss_awt_kernel_NativeLib_initialize(_P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_lowerWindow(Ljava/awt/peer/ComponentPeer;)V */
void
Kaffe_biss_awt_kernel_NativeLib_lowerWindow_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_lowerWindow(void*, void*);
	biss_awt_kernel_NativeLib_lowerWindow(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_raiseWindow(Ljava/awt/peer/ComponentPeer;)V */
void
Kaffe_biss_awt_kernel_NativeLib_raiseWindow_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_raiseWindow(void*, void*);
	biss_awt_kernel_NativeLib_raiseWindow(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_releaseFontMetrics(Ljava/awt/FontMetrics;)V */
void
Kaffe_biss_awt_kernel_NativeLib_releaseFontMetrics_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_releaseFontMetrics(void*, void*);
	biss_awt_kernel_NativeLib_releaseFontMetrics(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_releaseGraphics(Ljava/awt/Graphics;)V */
void
Kaffe_biss_awt_kernel_NativeLib_releaseGraphics_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_releaseGraphics(void*, void*);
	biss_awt_kernel_NativeLib_releaseGraphics(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_releaseImage(Ljava/awt/Image;)V */
void
Kaffe_biss_awt_kernel_NativeLib_releaseImage_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_releaseImage(void*, void*);
	biss_awt_kernel_NativeLib_releaseImage(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_releasePaintGraphics(Ljava/awt/Graphics;)V */
void
Kaffe_biss_awt_kernel_NativeLib_releasePaintGraphics_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_releasePaintGraphics(void*, void*);
	biss_awt_kernel_NativeLib_releasePaintGraphics(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_repaintWindow(Ljava/awt/peer/ComponentPeer;JIIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_repaintWindow_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_repaintWindow(void*, void*, jlong, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_repaintWindow(_P_[7].p, _P_[6].p, _P_[4].l, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_reshapeWindow(Ljava/awt/peer/ComponentPeer;IIII)V */
void
Kaffe_biss_awt_kernel_NativeLib_reshapeWindow_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_reshapeWindow(void*, void*, jint, jint, jint, jint);
	biss_awt_kernel_NativeLib_reshapeWindow(_P_[5].p, _P_[4].p, _P_[3].i, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_setColor(Ljava/awt/Graphics;Ljava/awt/Color;)V */
void
Kaffe_biss_awt_kernel_NativeLib_setColor_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_setColor(void*, void*, void*);
	biss_awt_kernel_NativeLib_setColor(_P_[2].p, _P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_setDebugLevel(I)V */
void
Kaffe_biss_awt_kernel_NativeLib_setDebugLevel_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_setDebugLevel(void*, jint);
	biss_awt_kernel_NativeLib_setDebugLevel(_P_[1].p, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_setFocusWindow(Ljava/awt/peer/ComponentPeer;)V */
void
Kaffe_biss_awt_kernel_NativeLib_setFocusWindow_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_setFocusWindow(void*, void*);
	biss_awt_kernel_NativeLib_setFocusWindow(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_setFont(Ljava/awt/Graphics;Ljava/awt/Font;)V */
void
Kaffe_biss_awt_kernel_NativeLib_setFont_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_setFont(void*, void*, void*);
	biss_awt_kernel_NativeLib_setFont(_P_[2].p, _P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_setPaintMode(Ljava/awt/Graphics;)V */
void
Kaffe_biss_awt_kernel_NativeLib_setPaintMode_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_setPaintMode(void*, void*);
	biss_awt_kernel_NativeLib_setPaintMode(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_setStdFontSpec(ILjava/lang/String;)V */
void
Kaffe_biss_awt_kernel_NativeLib_setStdFontSpec_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_setStdFontSpec(void*, jint, void*);
	biss_awt_kernel_NativeLib_setStdFontSpec(_P_[2].p, _P_[1].i, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_setWindowBackground(Ljava/awt/peer/ComponentPeer;Ljava/awt/Color;)V */
void
Kaffe_biss_awt_kernel_NativeLib_setWindowBackground_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_setWindowBackground(void*, void*, void*);
	biss_awt_kernel_NativeLib_setWindowBackground(_P_[2].p, _P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_setWindowCursor(Ljava/awt/peer/ComponentPeer;I)V */
void
Kaffe_biss_awt_kernel_NativeLib_setWindowCursor_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_setWindowCursor(void*, void*, jint);
	biss_awt_kernel_NativeLib_setWindowCursor(_P_[2].p, _P_[1].p, _P_[0].i);
}

/* SYMBOL: biss_awt_kernel_NativeLib_setWindowTitle(Ljava/awt/peer/ComponentPeer;Ljava/lang/String;)V */
void
Kaffe_biss_awt_kernel_NativeLib_setWindowTitle_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_setWindowTitle(void*, void*, void*);
	biss_awt_kernel_NativeLib_setWindowTitle(_P_[2].p, _P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_setXORMode(Ljava/awt/Graphics;)V */
void
Kaffe_biss_awt_kernel_NativeLib_setXORMode_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_setXORMode(void*, void*);
	biss_awt_kernel_NativeLib_setXORMode(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_showWindow(Ljava/awt/peer/ComponentPeer;)V */
void
Kaffe_biss_awt_kernel_NativeLib_showWindow_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_showWindow(void*, void*);
	biss_awt_kernel_NativeLib_showWindow(_P_[1].p, _P_[0].p);
}

/* SYMBOL: biss_awt_kernel_NativeLib_stringWidth(Ljava/awt/FontMetrics;Ljava/lang/String;)I */
void
Kaffe_biss_awt_kernel_NativeLib_stringWidth_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint biss_awt_kernel_NativeLib_stringWidth(void*, void*, void*);
	jint ret = biss_awt_kernel_NativeLib_stringWidth(_P_[2].p, _P_[1].p, _P_[0].p);
	return_int(ret);
}

/* SYMBOL: biss_awt_kernel_NativeLib_sync()V */
void
Kaffe_biss_awt_kernel_NativeLib_sync_stub(stack_item* _P_, stack_item* _R_)
{
	extern void biss_awt_kernel_NativeLib_sync(void*);
	biss_awt_kernel_NativeLib_sync(_P_[0].p);
}
