/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_Color
#define _Included_java_awt_Color

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_Color */

typedef struct Classjava_awt_Color {
  jint pData;
  jint value;
} Classjava_awt_Color;
HandleTo(java_awt_Color);


#ifdef __cplusplus
}
#endif

#endif
