/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_Insets
#define _Included_java_awt_Insets

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_Insets */

typedef struct Classjava_awt_Insets {
  jint top;
  jint left;
  jint bottom;
  jint right;
} Classjava_awt_Insets;
HandleTo(java_awt_Insets);


#ifdef __cplusplus
}
#endif

#endif
