/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_Rectangle
#define _Included_java_awt_Rectangle

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_Rectangle */

typedef struct Classjava_awt_Rectangle {
  jint x;
  jint y;
  jint width;
  jint height;
} Classjava_awt_Rectangle;
HandleTo(java_awt_Rectangle);


#ifdef __cplusplus
}
#endif

#endif
