/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_Font
#define _Included_java_awt_Font

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_Font */

typedef struct Classjava_awt_Font {
#define java_awt_Font_PLAIN 0
#define java_awt_Font_BOLD 1
#define java_awt_Font_ITALIC 2
  jint pData;
  struct Hjava_lang_String* family;
  struct Hjava_lang_String* name;
  jint style;
  jint size;
} Classjava_awt_Font;
HandleTo(java_awt_Font);


#ifdef __cplusplus
}
#endif

#endif
