/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_peer_ComponentPeer
#define _Included_java_awt_peer_ComponentPeer

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_peer_ComponentPeer */

typedef struct Classjava_awt_peer_ComponentPeer {
	int __DUMMY__;
} Classjava_awt_peer_ComponentPeer;
HandleTo(java_awt_peer_ComponentPeer);


#ifdef __cplusplus
}
#endif

#endif
