/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_awt_FontMetrics
#define _Included_java_awt_FontMetrics

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_awt_FontMetrics */

typedef struct Classjava_awt_FontMetrics {
  struct Hjava_awt_Font* font;
} Classjava_awt_FontMetrics;
HandleTo(java_awt_FontMetrics);


#ifdef __cplusplus
}
#endif

#endif
