/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APIAppAction -J ../classes/thotlib/APIAppAction.java ../thotlib/include/appaction.h 
 */
package thotlib;


/*
 * Java public native definitions for class thotlib_APIAppAction
 */

public class APIAppAction {
 public static final int NUMBER_OF_APP_EVENTS = 40;
 public static final int TTE_STANDARD_DELETE_FIRST_ITEMS = 0;
 public static final int TTE_STANDARD_DELETE_LAST_ITEM = 1;
 public static final int TTE_MERGE_DELETE_ITEM = 2;
 public static final int TTE_TOOLKIT_DELETE = 3;

 public static final int TteAttrMenu = 0;
 public static final int TteAttrCreate = 1;
 public static final int TteAttrModify = 2;
 public static final int TteAttrRead = 3;
 public static final int TteAttrSave = 4;
 public static final int TteAttrExport = 5;
 public static final int TteAttrDelete = 6;
 public static final int TteElemMenu = 7;
 public static final int TteElemNew = 8;
 public static final int TteElemRead = 9;
 public static final int TteElemSave = 10;
 public static final int TteElemExport = 11;
 public static final int TteElemDelete = 12;
 public static final int TteElemSelect = 13;
 public static final int TteElemExtendSelect = 14;
 public static final int TteElemActivate = 15;
 public static final int TteElemSetReference = 16;
 public static final int TteElemInclude = 17;
 public static final int TteElemCopy = 18;
 public static final int TteElemPaste = 19;
 public static final int TteElemChange = 20;
 public static final int TteElemMove = 21;
 public static final int TteElemTextModify = 22;
 public static final int TteElemGraphModify = 23;
 public static final int TteElemTransform = 24;
 public static final int TtePRuleCreate = 25;
 public static final int TtePRuleModify = 26;
 public static final int TtePRuleDelete = 27;
 public static final int TteDocOpen = 28;
 public static final int TteDocCreate = 29;
 public static final int TteDocClose = 30;
 public static final int TteDocSave = 31;
 public static final int TteDocExport = 32;
 public static final int TteViewOpen = 33;
 public static final int TteViewClose = 34;
 public static final int TteViewResize = 35;
 public static final int TteViewScroll = 36;
 public static final int TteInit = 37;
 public static final int TteExit = 38;
 public static final int TteNull = 39;

}
