/*
 * external_wrappers.h
 * Non-shared library wrapper for biss-net.com package.
 *
 * Copyright 1997 T. J. Wilkinson & Associates, London, UK.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * Modified by Tim Wilkinson <tim@tjwassoc.demon.co.uk>
 */

/* biss-net.com/APIawt */

KAFFE_NATIVE(biss_awt_kernel_NativeLib_clearRect)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_clipGraphics)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_copyArea)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_createWindow)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_destroyWindow)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_draw3DRect)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_drawArc)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_drawChars)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_drawImage)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_drawLine)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_drawOval)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_drawPolygon)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_drawRect)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_drawRoundRect)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_drawString)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_fillArc)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_fillOval)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_fillPolygon)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_fillRect)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_fillRoundRect)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_getNextEvent)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_getTargetBackground)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_getTargetFont)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_getTargetForeground)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_hideWindow)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_initBlankImage)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_initFontMetrics)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_initGraphics)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_initPaintGraphics)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_initStdColor)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_initialize)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_lowerWindow)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_raiseWindow)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_releaseFontMetrics)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_releaseGraphics)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_releaseImage)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_releasePaintGraphics)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_repaintWindow)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_reshapeWindow)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_setColor)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_setDebugLevel)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_setFocusWindow)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_setFont)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_setPaintMode)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_setStdFontSpec)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_setWindowBackground)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_setWindowCursor)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_setWindowTitle)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_setXORMode)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_showWindow)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_stringWidth)
KAFFE_NATIVE(biss_awt_kernel_NativeLib_sync)
