/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M amaya_APIAmayaMsg -J ../classes/amaya/APIAmayaMsg.java ../amaya/amayamsg.h 
 */
package amaya;


/*
 * Java public native definitions for class amaya_APIAmayaMsg
 */

public class APIAmayaMsg {
 public static final int AM_FILES = 0;
 public static final int AM_OPEN_URL = 1;
 public static final int AM_CLEAR = 2;
 public static final int AM_SAVED = 3;
 public static final int AM_ATTRIBUTE = 4;
 public static final int AM_HREF_VALUE = 5;
 public static final int AM_TEXT = 6;
 public static final int AM_NAME = 7;
 public static final int AM_PASSWORD = 8;
 public static final int AM_DEF_CLASS = 9;
 public static final int AM_APPLY_CLASS = 10;
 public static final int AM_SEL_CLASS = 11;
 public static final int AM_FETCHING = 12;
 public static final int AM_CANNOT_LOAD = 13;
 public static final int AM_DOCUMENT_LOADED = 14;
 public static final int AM_SEL_TARGET = 15;
 public static final int AM_INVALID_TARGET = 16;
 public static final int AM_LOCATION = 17;
 public static final int AM_TITLE = 18;
 public static final int AM_DOC_MODIFIED = 19;
 public static final int AM_RED_FETCHING = 20;
 public static final int AM_REDIRECTIONS_LIMIT = 21;
 public static final int AM_CANNOT_CREATE_FILE = 22;
 public static final int AM_WAITING_FOR_SOCKET = 23;
 public static final int AM_PROG_READ = 24;
 public static final int AM_PROG_WRITE = 25;
 public static final int AM_WAITING_FOR_CONNECTION = 26;
 public static final int AM_CONTACTING_HOST = 27;
 public static final int AM_LOOKING_HOST = 28;
 public static final int AM_UNKNOWN_STATUS = 29;
 public static final int AM_GET_AUTHENTICATION = 30;
 public static final int AM_AUTHENTICATION_FAILURE = 31;
 public static final int AM_LOADED_NO_DATA = 32;
 public static final int AM_LOAD_ABORT = 33;
 public static final int AM_NOT_AVAILABLE_RETRY = 34;
 public static final int AM_ELEMENT_LOADED = 35;
 public static final int AM_REMOTE_SAVING = 36;
 public static final int AM_CANNOT_SAVE = 37;
 public static final int AM_SYSTEM_ERROR = 38;
 public static final int AM_INVALID_ANCHOR1 = 39;
 public static final int AM_INVALID_ANCHOR2 = 40;
 public static final int AM_GET_UNSUPPORTED_PROTOCOL = 41;
 public static final int AM_PUT_UNSUPPORTED_PROTOCOL = 42;
 public static final int AM_UNSUPPORTED_FEATURE = 43;
 public static final int AM_WROTE_OBJECT = 44;
 public static final int AM_BAD_URL = 45;
 public static final int AM_CACHE_ERROR = 46;
 public static final int AM_NO_TRANS = 47;
 public static final int AM_TRANS_FAILED = 48;
 public static final int AM_TRANS_PARSE_ERROR = 49;
 public static final int AM_ADD = 50;
 public static final int AM_SHOW = 51;
 public static final int AM_BROWSE = 52;
 public static final int AM_EXTERNAL_CSS = 53;
 public static final int AM_DELETE_CSS = 54;
 public static final int AM_DELETE = 55;
 public static final int AM_SAVE = 56;
 public static final int AM_SAVE_AS = 57;
 public static final int AM_RELOAD = 58;
 public static final int AM_NEW = 59;
 public static final int AM_CSS = 60;
 public static final int AM_WARNING_SAVE_OVERWRITE = 61;
 public static final int AM_URL_SAVE_FAILED = 62;
 public static final int AM_SAVE_DISK = 63;
 public static final int AM_BCOPY_IMAGES = 64;
 public static final int AM_BTRANSFORM_URL = 65;
 public static final int AM_DOC_LOCATION = 66;
 public static final int AM_IMAGES_LOCATION = 67;
 public static final int AM_OBJECT_LOCATION = 68;
 public static final int AM_DOC_STYLE = 69;
 public static final int AM_USER_PREFERENCES = 70;
 public static final int AM_CSS_FILE_1 = 71;
 public static final int AM_RULE_LIST_FILE_1 = 72;
 public static final int AM_CSS_FILE_2 = 73;
 public static final int AM_RULE_LIST_FILE_2 = 74;
 public static final int AM_SELECT_EXTERNAL_STYLE_SHEET = 75;
 public static final int AM_DELETE_STYLE_SHEET = 76;
 public static final int AM_SYS_ERROR_TMPL = 77;
 public static final int AM_GET_USER_NAME = 78;
 public static final int AM_WAITING_REQUESTS = 79;
 public static final int AM_CACHE_GC = 80;
 public static final int AM_BUTTON_INTERRUPT = 81;
 public static final int AM_BUTTON_PREVIOUS = 82;
 public static final int AM_BUTTON_NEXT = 83;
 public static final int AM_BUTTON_RELOAD = 84;
 public static final int AM_BUTTON_SAVE = 85;
 public static final int AM_BUTTON_PRINT = 86;
 public static final int AM_BUTTON_SEARCH = 87;
 public static final int AM_BUTTON_ITALICS = 88;
 public static final int AM_BUTTON_BOLD = 89;
 public static final int AM_BUTTON_CODE = 90;
 public static final int AM_BUTTON_CSS = 91;
 public static final int AM_BUTTON_IMG = 92;
 public static final int AM_BUTTON_H1 = 93;
 public static final int AM_BUTTON_H2 = 94;
 public static final int AM_BUTTON_H3 = 95;
 public static final int AM_BUTTON_UL = 96;
 public static final int AM_BUTTON_OL = 97;
 public static final int AM_BUTTON_DL = 98;
 public static final int AM_BUTTON_LINK = 99;
 public static final int AM_BUTTON_TABLE = 100;
 public static final int AM_NO_NAME = 101;
 public static final int AM_BUTTON_PLUGIN = 102;
 public static final int AM_UNKNOWN_SAVE_ERROR = 103;
 public static final int AM_CANT_CONNECT_TO_HOST = 104;
 public static final int AM_FORBIDDEN_ACCESS = 105;
 public static final int AM_REQUEST_SUCCEEDED = 106;
 public static final int AM_CREATED_NEW_REMOTE_RESSOURCE = 107;
 public static final int AM_UPDATED_REMOTE_RESSOURCE = 108;
 public static final int AM_UNKNOWN_XXX_STATUS = 109;
 public static final int AM_SERVER_DID_NOT_UNDERSTAND_REQ_SYNTAX = 110;
 public static final int AM_NO_DATA = 111;
 public static final int AM_METHOD_NOT_ALLOWED = 112;
 public static final int AM_PLEASE_AUTHENTICATE = 113;
 public static final int AM_VERIFYING = 114;
 public static final int AM_SAVING_FAILED = 115;
 public static final int AM_SAVE_COMPARE_FAILED = 116;
 public static final int AM_SAVE_REDIRECTED = 117;
 public static final int AM_SAVE_RELOAD_FAILED = 118;
 public static final int AM_SERVER_INTERNAL_ERROR_500_CAUSE = 119;
 public static final int AM_SERVER_INTERNAL_ERROR_500_NO_CAUSE = 120;
 public static final int AM_SERVER_NOT_IMPLEMENTED_501_ERROR = 121;
 public static final int AM_PARSE = 122;
 public static final int AM_ACTIVE_TRANSFERS = 123;
 public static final int AM_WAITING_TRANSFERS = 124;
 public static final int AM_PRINT_TOC = 125;
 public static final int AM_NUMBERED_LINKS = 126;
 public static final int AM_BUTTON_JAVA = 127;
 public static final int AM_REPEAT_MODE = 128;
 public static final int AM_REPEAT = 129;
 public static final int AM_REPEAT_X = 130;
 public static final int AM_REPEAT_Y = 131;
 public static final int AM_NO_REPEAT = 132;
 public static final int AMAYA_MSG_MAX = 133;

}
