/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M amaya_APIJavaAmaya -J ../classes/amaya/APIJavaAmaya.java ../amaya/javaamaya.h 
 */
package amaya;


/*
 * Java public native definitions for class amaya_APIJavaAmaya
 */

public class APIJavaAmaya {


/*
 * Part of the interface extracted from init.c
 */
 public static native int IsDocumentLoaded(String documentURL);
 public static native void ExtractParameters(String aName, String parameters);
 public static native void ExtractSuffix(String aName, String aSuffix);
 public static native void ResetStop(int document);
 public static native void ActiveTransfer(int document);
 public static native void StopTransfer(int document, int view);
 public static native void SetCharEmphasis(int document, int view);
 public static native void SetCharStrong(int document, int view);
 public static native void SetCharCode(int document, int view);
 public static native void InitFormAnswer(int document, int view);
 public static native void InitConfirm(int document, int view, String label);
 public static native void OpenDocInNewWindow(int document, int view);
 public static native void OpenDoc(int document, int view);
 public static native void Reload(int document, int view);
 public static native void ShowStructure(int document, int view);
 public static native void ShowAlternate(int document, int view);
 public static native void ShowLinks(int document, int view);
 public static native void ShowToC(int document, int view);
 public static native void ShowMapAreas(int document, int view);
 public static native boolean NormalizeFile(String src, String target);
 public static native void SectionNumbering(int document, int view);
 public static native void MakeBook(int document, int view);
 public static native void RealTimeHTML(int document, int view);
 public static native void HelpAmaya(int document, int view);
 public static native void AmayaClose(int document, int view);


/*
 * Part of the interface extracted from javaamaya.c
 */
 public static native String GetUserAgentName();
 public static native String GetDocumentURL(int doc);
 public static native String AmayaGetMessage(int msg);
 public static native int PopUpAuthDialog(int doc);
 public static native String GetUserString();
 public static native String GetPasswdString();
 public static native String GetAnswerString();
 public static native String GetTempDirectory();
}
