/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APIApplication -J ../classes/thotlib/APIApplication.java ../thotlib/include/application.h 
 */
package thotlib;


/*
 * Java public native definitions for class thotlib_APIApplication
 */

public class APIApplication {
 public static final int ERR_document_name = 1;
 public static final int ERR_too_many_documents = 2;
 public static final int ERR_cannot_read_struct_schema = 3;
 public static final int ERR_empty_document = 4;
 public static final int ERR_cannot_open_pivot_file = 5;
 public static final int ERR_invalid_document_parameter = 6;
 public static final int ERR_read_only_document = 8;
 public static final int ERR_invalid_associated_root = 9;
 public static final int ERR_invalid_parameter = 10;
 public static final int ERR_not_implemented = 11;
 public static final int ERR_invalid_attribute_value = 12;
 public static final int ERR_attribute_element_mismatch = 14;
 public static final int ERR_buffer_too_small = 15;
 public static final int ERR_invalid_element_type = 16;
 public static final int ERR_element_does_not_match_DTD = 17;
 public static final int ERR_invalid_attribute_type = 18;
 public static final int ERR_duplicate_attribute = 19;
 public static final int ERR_mandatory_attribute = 20;
 public static final int ERR_cannot_set_link = 21;
 public static final int ERR_no_selection_in_document = 22;
 public static final int ERR_incorrect_tree = 23;
 public static final int ERR_cannot_open_view = 24;
 public static final int ERR_there_are_open_views = 25;
 public static final int ERR_cannot_load_pschema = 26;
 public static final int ERR_duplicate_presentation_rule = 27;
 public static final int ERR_string_too_long = 28;
 public static final int ERR_cannot_holophrast_a_root = 29;
 public static final int ERR_cannot_holophrast_that_type = 30;
 public static final int ERR_main_window_not_open = 31;
 public static final int ERR_element_already_inserted = 32;
 public static final int ERR_no_presentation_schema = 33;
 public static final int ERR_element_has_no_box = 34;
 public static final int ERR_no_selection_in_view = 35;
 public static final int ERR_invalid_X_connection = 50;
 public static final int ERR_cannot_open_main_window = 51;
 public static final int ERR_invalid_button = 52;
 public static final int ERR_cannot_create_dialogue = 53;
 public static final int ERR_invalid_parent_dialogue = 54;
 public static final int ERR_invalid_reference = 55;
 public static final int ERR_too_many_languages = 100;
 public static final int ERR_language_not_found = 101;



/*----------------------------------------------------------------------
   TtaInitialize

   Initializes the Thot editing tool kit for an application. This function must be
   called before any other function of the tool kit.

   Parameter:
   applicationName: the argv[0] of the application that requires services
   from the tool kit.  This name is used for accessing the ressources
   defined in file .Xdefaults.

  ----------------------------------------------------------------------*/
 public static native void TtaInitialize(String applicationName);


/*----------------------------------------------------------------------
   TtaQuit

   Quits the Thot tool kit. No other function of the tool kit can then
   be called by the application.

  ----------------------------------------------------------------------*/
 public static native void TtaQuit();


/*----------------------------------------------------------------------
   TtaSetErrorMessages

   Indicates to the tool kit whether error messages must be printed or not.

   Parameter:
   on: 1 if error messages must be printed, 0 if not.

  ----------------------------------------------------------------------*/
 public static native void TtaSetErrorMessages(int on);


/*----------------------------------------------------------------------
   TtaGetVersion

   Returns the identifier of the current version of the Thot editing tool kit.

   Return value:
   identifier of the current version.

  ----------------------------------------------------------------------*/
 public static native String TtaGetVersion();


/*----------------------------------------------------------------------
   TtaGetErrorCode

   Returns the error code set by the last call to the Thot editing tool kit.
   See file application.h for the possible values.

   Return value:
   last error code, 0 if the last call was successful.

  ----------------------------------------------------------------------*/
 public static native int TtaGetErrorCode();


/*----------------------------------------------------------------------
   TtaGetStrError

   Returns a pointer to the message text for a given error code.

   Parameter:
   errorCode: an error code.

   Return value:
   No return value

   See also:
   TtaGetErrorCode
  ----------------------------------------------------------------------*/
 public static native String TtaGetStrError(int errorCode);


/*----------------------------------------------------------------------
   TtaExtractName: extracts the directory and the file name.       
   aDirectory and aName must be arrays of characters       
   which sizes are sufficient to contain the path and      
   the file name.                                          
  ----------------------------------------------------------------------*/
 public static native void TtaExtractName(String text, /*OUT*/ StringBuffer aDirectory, /*OUT*/ StringBuffer aName);


/*----------------------------------------------------------------------
   TtaCheckDirectory

   Ckecks that a directory exists and can be accessed.

   Parameter:
   directory: the directory name.
   Return value:
   TRUE if the directory is OK, FALSE if not.
	
  ----------------------------------------------------------------------*/
 public static native boolean TtaCheckDirectory(String aDirectory);
 public static native String TtaStrdup(String str);
}
