/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APIInterface -J ../classes/thotlib/APIInterface.java ../thotlib/include/interface.h 
 */
package thotlib;


/*
 * Java public native definitions for class thotlib_APIInterface
 */

public class APIInterface {
 public static final int ISO_1_keyboard = 0;
 public static final int Greek_keyboard = 1;
 public static final int Symbol_keyboard = 2;
 public static final int Graphic_keyboard = 3;



/*----------------------------------------------------------------------
   TtaSwitchButton

   Change the status of the button entry in a document view.
   This function must specify a valid view of a valid document.

   Parameters:
   document: the concerned document.
   view: the concerned view.
   index: the index.
  ----------------------------------------------------------------------*/
 public static native void TtaSwitchButton(int document, int view, int index);


/*----------------------------------------------------------------------
   TtaChangeButton

   Change the button entry in a document view.
   This function must specify a valid view of a valid document.

   Parameters:
   document: the concerned document.
   view: the concerned view.
   index: the index.
   picture: the new icon.
  ----------------------------------------------------------------------*/
 public static native void TtaChangeButton(int document, int view, int index, long picture);


/*----------------------------------------------------------------------
   TtaSetTextZone

   Sets the text in text-zone in a document view.
   This function must specify a valid view of a valid document.

   Parameters:
   document: identifier of the document.
   view: identifier of the view.
   index: 

  ----------------------------------------------------------------------*/
 public static native void TtaSetTextZone(int document, int view, int index, String text);


/*----------------------------------------------------------------------
   TtaSetMenuOff desactive le menu (1 a n) de la vue du document ou   
   de la fenetre principale (document = 0, view = 0).                 
  ----------------------------------------------------------------------*/
 public static native void TtaSetMenuOff(int document, int view, int menuID);


/*----------------------------------------------------------------------
   TtaSetMenuOn reactive le menu (1 a n) de la vue du document ou     
   de la fenetre principale (document = 0, view = 0).                 
  ----------------------------------------------------------------------*/
 public static native void TtaSetMenuOn(int document, int view, int menuID);


/*----------------------------------------------------------------------
   TtaSetToggleItem positionne l'item du menu de la vue du document   
   ou de la fenetre principale (document = 0, view = 0).   
  ----------------------------------------------------------------------*/
 public static native void TtaSetToggleItem(int document, int view, int menuID, int itemID, boolean on);


/*----------------------------------------------------------------------
   TtaSetActionOff desactive l'item actionName de la vue du document  
   ou de la fenetre principale (document = 0, view = 0).   
  ----------------------------------------------------------------------*/
 public static native void TtaSetActionOff(int document, int view, int menuID, int itemID);


/*----------------------------------------------------------------------
   TtaSetActionOn active l'item actionName de la vue du document      
   ou de la fenetre principale (document = 0, view = 0).   
  ----------------------------------------------------------------------*/
 public static native void TtaSetActionOn(int document, int view, int menuID, int itemID);


/*----------------------------------------------------------------------
   TtaSetStatus affiche le status de la vue du document.                      
  ----------------------------------------------------------------------*/
 public static native void TtaSetStatus(int document, int view, String text, String name);


/*----------------------------------------------------------------------
   TtaGetViewFrame retourne le widget du frame de la vue document.    
  ----------------------------------------------------------------------*/
 public static native long TtaGetViewFrame(int document, int view);


/* !_WINDOWS */
 public static native void TtaMainLoop();


/*----------------------------------------------------------------------
   * TtaHandlePendingEvents
 *
   * Processes all pending events in an application.
  ----------------------------------------------------------------------*/
 public static native void TtaHandlePendingEvents();


/*----------------------------------------------------------------------
   TtaCreateBitmapLogo

   Creates a logo pixmap from a bitmap description: width, height and bit array.

   Parameters:
   width: the width value of the bitmap.
   height: the height value of the bitmap.
   bits: the bit array.

   Return value:
   The created pixmap for the logo.

  ----------------------------------------------------------------------*/
 public static native long TtaCreateBitmapLogo(int width, int height, String bits);
 public static native void TtaSetCursorWatch(int document, int view);
 public static native void TtaResetCursor(int document, int view);


/*----------------------------------------------------------------------
   TtaGetMenuColor

   Returns the color used for the background of dialogue windows.
  ----------------------------------------------------------------------*/
 public static native int TtaGetMenuColor();


/*----------------------------------------------------------------------
   TtaGetButtonColor

   Returns the color used for displaying active buttons in forms.

  ----------------------------------------------------------------------*/
 public static native int TtaGetButtonColor();


/*----------------------------------------------------------------------
   TtaGetScreenDepth

   Returns the current screen depth.

  ----------------------------------------------------------------------*/
 public static native int TtaGetScreenDepth();


/*----------------------------------------------------------------------
   TtaGiveSelectPosition: returns the mouse position for the last click 
   with respect to the element (position in pixel)            
  ----------------------------------------------------------------------*/
 public static native void TtaGiveSelectPosition(int document, long element, int view, /*OUT*/ IntPtr X, /*OUT*/ IntPtr Y);


/*----------------------------------------------------------------------
   TtaRegisterPixmap

   Register a pre-loaded Pixmap into the database.

   Parameters:
   name : the name of the image.
   pix : pointer to the existing pixmap.

   Return value:
   none

  ----------------------------------------------------------------------*/
 public static native void TtaRegisterPixmap(String name, long pix);


/*----------------------------------------------------------------------
   TtaLoadImage

   Load an image from disk into the database.

   Parameters:
   name : the name of the image.
   path : the full pathname referencing the image file.

   Return value:
   The created pixmap

  ----------------------------------------------------------------------*/
 public static native long TtaLoadImage(String name, String path);


/*----------------------------------------------------------------------
   TtaGetImage

   Get an image from the database.

   Parameters:
   name : the name of the image.

   Return value:
   The pixmap or NULL if not found.

  ----------------------------------------------------------------------*/
 public static native long TtaGetImage(String name);
}
