/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APIRegistry -J ../classes/thotlib/APIRegistry.java ../thotlib/include/registry.h 
 */
package thotlib;


/*
 * Java public native definitions for class thotlib_APIRegistry
 */

public class APIRegistry {


/*
 * TtaInitializeAppRegistry : initialize the Registry, the only argument
 *       given is a copy of the argv[0] received from the main().
 *       From this, we can deduce the installation directory of the programm,
 *       (using the PATH environment value if necessary) and the application
 *       name.
 *       We load the ressources file from the installation directory and
 *       the specific user values from the user HOME dir.
 */
 public static native void TtaInitializeAppRegistry(String appArgv0);


/*
 * TtaGetEnvString : read the value associated to an environment string
 *                  if not present return NULL.
 */
 public static native String TtaGetEnvString(String name);


/*
 * TtaSetEnvString : set the value associated to an environment string,
 *                  for the current application.
 */
 public static native void TtaSetEnvString(String name, String value, int overwrite);


/*
 * TtaSaveAppRegistry : Save the Registry in the THOT_RC_FILENAME located
 *       in the user's directory.
 */
 public static native void TtaSaveAppRegistry();
}
