/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Class
#define _Included_java_lang_Class

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Class */

typedef struct Classjava_lang_Class {
	int __DUMMY__;
} Classjava_lang_Class;
HandleTo(java_lang_Class);

extern struct Hjava_lang_Class* java_lang_Class_forName(struct Hjava_lang_Class*, struct Hjava_lang_String*);
extern struct Hjava_lang_Object* java_lang_Class_newInstance(struct Hjava_lang_Class*);
extern struct Hjava_lang_String* java_lang_Class_getName(struct Hjava_lang_Class*);
extern struct Hjava_lang_Class* java_lang_Class_getSuperclass(struct Hjava_lang_Class*);
extern HArrayOfObject* java_lang_Class_getInterfaces(struct Hjava_lang_Class*);
extern struct Hjava_lang_ClassLoader* java_lang_Class_getClassLoader(struct Hjava_lang_Class*);
extern jint /* bool */ java_lang_Class_isInterface(struct Hjava_lang_Class*);

#ifdef __cplusplus
}
#endif

#endif
