/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Compiler */

/* SYMBOL: java_lang_Compiler_initialize()V */
void
Kaffe_java_lang_Compiler_initialize_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Compiler_initialize(void*);
	java_lang_Compiler_initialize(0);
}

/* SYMBOL: java_lang_Compiler_compileClass(Ljava/lang/Class;)Z */
void
Kaffe_java_lang_Compiler_compileClass_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint /* bool */ java_lang_Compiler_compileClass(void*, void*);
	jint /* bool */ ret = java_lang_Compiler_compileClass(0, _P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Compiler_compileClasses(Ljava/lang/String;)Z */
void
Kaffe_java_lang_Compiler_compileClasses_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint /* bool */ java_lang_Compiler_compileClasses(void*, void*);
	jint /* bool */ ret = java_lang_Compiler_compileClasses(0, _P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Compiler_command(Ljava/lang/Object;)Ljava/lang/Object; */
void
Kaffe_java_lang_Compiler_command_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* java_lang_Compiler_command(void*, void*);
	struct Hjava_lang_Object* ret = java_lang_Compiler_command(0, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Compiler_enable()V */
void
Kaffe_java_lang_Compiler_enable_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Compiler_enable(void*);
	java_lang_Compiler_enable(0);
}

/* SYMBOL: java_lang_Compiler_disable()V */
void
Kaffe_java_lang_Compiler_disable_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Compiler_disable(void*);
	java_lang_Compiler_disable(0);
}
