/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Double
#define _Included_java_lang_Double

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Double */

typedef struct Classjava_lang_Double {
#define java_lang_Double_POSITIVE_INFINITY Inf
#define java_lang_Double_NEGATIVE_INFINITY -Inf
#define java_lang_Double_NaN NaN
#define java_lang_Double_MAX_VALUE 1.79769e+308
#define java_lang_Double_MIN_VALUE 2.22507e-308
  jdouble value;
} Classjava_lang_Double;
HandleTo(java_lang_Double);

extern struct Hjava_lang_String* java_lang_Double_toString(struct Hjava_lang_Double*, jdouble);
extern struct Hjava_lang_Double* java_lang_Double_valueOf(struct Hjava_lang_Double*, struct Hjava_lang_String*);
extern jlong java_lang_Double_doubleToLongBits(struct Hjava_lang_Double*, jdouble);
extern jdouble java_lang_Double_longBitsToDouble(struct Hjava_lang_Double*, jlong);

#ifdef __cplusplus
}
#endif

#endif
