/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Float */

/* SYMBOL: java_lang_Float_toString(F)Ljava/lang/String; */
void
Kaffe_java_lang_Float_toString_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_lang_Float_toString(void*, jfloat);
	struct Hjava_lang_String* ret = java_lang_Float_toString(0, _P_[0].f);
	return_ref(ret);
}

/* SYMBOL: java_lang_Float_valueOf(Ljava/lang/String;)Ljava/lang/Float; */
void
Kaffe_java_lang_Float_valueOf_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Float* java_lang_Float_valueOf(void*, void*);
	struct Hjava_lang_Float* ret = java_lang_Float_valueOf(0, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Float_floatToIntBits(F)I */
void
Kaffe_java_lang_Float_floatToIntBits_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_Float_floatToIntBits(void*, jfloat);
	jint ret = java_lang_Float_floatToIntBits(0, _P_[0].f);
	return_int(ret);
}

/* SYMBOL: java_lang_Float_intBitsToFloat(I)F */
void
Kaffe_java_lang_Float_intBitsToFloat_stub(stack_item* _P_, stack_item* _R_)
{
	extern jfloat java_lang_Float_intBitsToFloat(void*, jint);
	jfloat ret = java_lang_Float_intBitsToFloat(0, _P_[0].i);
	return_float(ret);
}
