/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Math
#define _Included_java_lang_Math

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Math */

typedef struct Classjava_lang_Math {
#define java_lang_Math_E 2.71828
#define java_lang_Math_PI 3.14159
	int __DUMMY__;
} Classjava_lang_Math;
HandleTo(java_lang_Math);

extern jdouble java_lang_Math_sin(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_cos(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_tan(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_asin(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_acos(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_atan(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_exp(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_log(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_sqrt(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_IEEEremainder(struct Hjava_lang_Math*, jdouble, jdouble);
extern jdouble java_lang_Math_ceil(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_floor(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_rint(struct Hjava_lang_Math*, jdouble);
extern jdouble java_lang_Math_atan2(struct Hjava_lang_Math*, jdouble, jdouble);
extern jdouble java_lang_Math_pow(struct Hjava_lang_Math*, jdouble, jdouble);

#ifdef __cplusplus
}
#endif

#endif
