/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_System
#define _Included_java_lang_System

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_System */

typedef struct Classjava_lang_System {
	int __DUMMY__;
} Classjava_lang_System;
HandleTo(java_lang_System);

extern jlong java_lang_System_currentTimeMillis(struct Hjava_lang_System*);
extern void java_lang_System_arraycopy(struct Hjava_lang_System*, struct Hjava_lang_Object*, jint, struct Hjava_lang_Object*, jint, jint);
extern struct Hjava_util_Properties* java_lang_System_initProperties(struct Hjava_lang_System*, struct Hjava_util_Properties*);

#ifdef __cplusplus
}
#endif

#endif
