/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_UNIXProcess */

/* SYMBOL: java_lang_UNIXProcess_exec([Ljava/lang/String;[Ljava/lang/String;)V */
void
Kaffe_java_lang_UNIXProcess_exec_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_UNIXProcess_exec(void*, HArrayOfObject*, HArrayOfObject*);
	java_lang_UNIXProcess_exec(_P_[2].p, _P_[1].p, _P_[0].p);
}

/* SYMBOL: java_lang_UNIXProcess_fork()I */
void
Kaffe_java_lang_UNIXProcess_fork_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_UNIXProcess_fork(void*);
	jint ret = java_lang_UNIXProcess_fork(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_UNIXProcess_waitForUNIXProcess()I */
void
Kaffe_java_lang_UNIXProcess_waitForUNIXProcess_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_UNIXProcess_waitForUNIXProcess(void*);
	jint ret = java_lang_UNIXProcess_waitForUNIXProcess(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_UNIXProcess_destroy()V */
void
Kaffe_java_lang_UNIXProcess_destroy_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_UNIXProcess_destroy(void*);
	java_lang_UNIXProcess_destroy(_P_[0].p);
}
