PACKAGE  = "w3c.www.protocol.http.icp"

FILES = \
	ICP.java \
	ICPMessage.java \
	ICPQuery.java \
	ICPReply.java \
	ICPFilter.java \
	ICPProtocolException.java \
	ICPWaiter.java \
	ICPSender.java \
	ICPReceiver.java

include $(MAKEDIR)/file.make
