PACKAGE = "w3c.www.protocol.http.cache"

FILES = \
	CacheFilter.java \
	CachedResource.java \
	CacheState.java \
	ActiveStream.java \
	TeeMonitor.java \
	CachedResourceFactory.java \
	CacheSweeper.java \
	VaryResource.java \
	cacheStatistics.java \
	CachedResourceFactory.java

include $(MAKEDIR)/file.make
